// AUTO-GENERATED by scripts/gtk-typegen.ts -- do not edit by hand.
// Re-run with scripts/gtk-typegen.sh whenever the theme or icon theme changes.

export type { ThemeColor } from "./colors";
export type { SymbolicIconName } from "./icons";
export type { NiceWidgetProps } from "./types";
