// AUTO-GENERATED by scripts/gtk-typegen.ts -- do not edit by hand.
// Re-run with scripts/gtk-typegen.sh whenever the theme or icon theme changes.

/**
 * GTK's named theme colors, usable as `@name` in GTK CSS (e.g.
 * "alpha(@theme_fg_color, 0.5)"). Verified live against the running
 * theme -- see scripts/gtk-typegen.ts for the candidate list and why
 * this can't be enumerated from GTK's API directly.
 */
export type ThemeColor =
  | "accent_color"
  | "borders"
  | "content_view_bg"
  | "error_color"
  | "insensitive_base_color"
  | "insensitive_bg_color"
  | "insensitive_fg_color"
  | "success_color"
  | "theme_base_color"
  | "theme_bg_color"
  | "theme_fg_color"
  | "theme_selected_bg_color"
  | "theme_selected_fg_color"
  | "theme_text_color"
  | "theme_unfocused_base_color"
  | "theme_unfocused_bg_color"
  | "theme_unfocused_fg_color"
  | "theme_unfocused_selected_bg_color"
  | "theme_unfocused_selected_fg_color"
  | "theme_unfocused_text_color"
  | "unfocused_borders"
  | "unfocused_insensitive_color"
  | "warning_color";
