import { Gdk, Gtk } from "ags/gtk4";
import app from "ags/gtk4/app";
import GLib from "gi://GLib";

/**
 * Candidate GTK theme colors to test against the live theme. There's no
 * GObject Introspection API to enumerate "every defined color" -- named
 * colors are just custom idents the active theme happens to define, not
 * part of GTK's own API -- so this list is a best-effort superset (classic
 * GTK named colors + libadwaita's, which only resolve when libadwaita is
 * loaded). Each candidate is verified live via
 * `Gtk.StyleContext.lookup_color()`; only the ones that actually resolve
 * end up in the generated type. A name GTK adds later that isn't listed
 * here won't be picked up -- add it below and re-run.
 */
const COLOR_CANDIDATES = [
  "theme_fg_color",
  "theme_bg_color",
  "theme_base_color",
  "theme_text_color",
  "theme_selected_bg_color",
  "theme_selected_fg_color",
  "theme_unfocused_fg_color",
  "theme_unfocused_bg_color",
  "theme_unfocused_base_color",
  "theme_unfocused_text_color",
  "theme_unfocused_selected_bg_color",
  "theme_unfocused_selected_fg_color",
  "insensitive_fg_color",
  "insensitive_bg_color",
  "insensitive_base_color",
  "unfocused_insensitive_color",
  "theme_selected_borders_color",
  "theme_unfocused_borders_color",
  "borders",
  "unfocused_borders",
  "warning_color",
  "error_color",
  "success_color",
  "link_color",
  "visited_link_color",
  "content_view_bg",
  "placeholder_text_color",
  "wm_title_focused",
  "wm_title_unfocused",
  "wm_icons_focused",
  "wm_icons_unfocused",
  "wm_bg_focused",
  "wm_bg_unfocused",
  "wm_border_focused",
  "wm_border_unfocused",
  "accent_color",
  "accent_bg_color",
  "accent_fg_color",
  "destructive_color",
  "destructive_bg_color",
  "destructive_fg_color",
  "success_bg_color",
  "success_fg_color",
  "warning_bg_color",
  "warning_fg_color",
  "error_bg_color",
  "error_fg_color",
  "window_bg_color",
  "window_fg_color",
  "view_bg_color",
  "view_fg_color",
  "headerbar_bg_color",
  "headerbar_fg_color",
  "headerbar_border_color",
  "headerbar_backdrop_color",
  "headerbar_shade_color",
  "card_bg_color",
  "card_fg_color",
  "card_shade_color",
  "dialog_bg_color",
  "dialog_fg_color",
  "popover_bg_color",
  "popover_fg_color",
  "popover_shade_color",
  "shade_color",
  "scrollbar_outline_color",
  "sidebar_bg_color",
  "sidebar_fg_color",
  "sidebar_backdrop_color",
  "sidebar_border_color",
  "sidebar_shade_color",
  "secondary_sidebar_bg_color",
  "secondary_sidebar_fg_color",
  "secondary_sidebar_backdrop_color",
  "secondary_sidebar_border_color",
  "secondary_sidebar_shade_color",
];

const GENERATED_HEADER =
  "// AUTO-GENERATED by scripts/gtk-typegen.ts -- do not edit by hand.\n" +
  "// Re-run with scripts/gtk-typegen.sh whenever the theme or icon theme changes.\n";

const writeUnionType = (
  path: string,
  exportName: string,
  doc: string,
  values: string[],
) => {
  const lines = [GENERATED_HEADER, doc, `export type ${exportName} =`];

  values.forEach((value, index) => {
    lines.push(`  ${index === 0 ? " " : "|"} "${value}"`);
  });
  lines[lines.length - 1] += ";";

  GLib.file_set_contents(path, lines.join("\n") + "\n");
};

app.start({
  instanceName: "gtk-typegen",
  main: () => {
    // get_style_context()/lookup_color() are deprecated since GTK 4.10 and
    // documented to be removed in GTK 5, with no redirect to a replacement
    // (unlike e.g. get_color() -> Gtk.Widget.get_color()) -- GTK's named
    // `@color` lookup mechanism itself is being replaced by standard CSS
    // custom properties, which only resolve in context and aren't
    // queryable in isolation. There's currently no GTK5-safe way to ask
    // "does a color named X exist"; this is a dev-time generator script,
    // not runtime code, so it's fine to keep relying on this until GTK
    // ships an alternative.
    const styleContext = new Gtk.Box().get_style_context();

    const colors = COLOR_CANDIDATES.filter(
      (name) => styleContext.lookup_color(name)[0],
    ).sort();

    const iconTheme = Gtk.IconTheme.get_for_display(Gdk.Display.get_default()!);
    const icons = [...new Set(iconTheme.get_icon_names())]
      .filter((name) => name.endsWith("-symbolic"))
      .sort();

    writeUnionType(
      "../lib/gtk/colors.d.ts",
      "ThemeColor",
      "/**\n" +
        " * GTK's named theme colors, usable as `@name` in GTK CSS (e.g.\n" +
        ' * "alpha(@theme_fg_color, 0.5)"). Verified live against the running\n' +
        " * theme -- see scripts/gtk-typegen.ts for the candidate list and why\n" +
        " * this can't be enumerated from GTK's API directly.\n" +
        " */",
      colors,
    );

    writeUnionType(
      "../lib/gtk/icons.d.ts",
      "IconName",
      "/**\n" +
        " * Symbolic icon names available in the active icon theme, per\n" +
        " * `Gtk.IconTheme.get_for_display(...).get_icon_names()`. This is a\n" +
        " * snapshot of the icon theme active when this was generated -- it\n" +
        " * will drift if the icon theme changes, and won't match on another\n" +
        " * machine.\n" +
        " */",
      icons,
    );

    GLib.file_set_contents(
      "../lib/gtk/index.d.ts",
      GENERATED_HEADER +
        "\n" +
        'export type { ThemeColor } from "./colors";\n' +
        'export type { IconName } from "./icons";\n',
    );

    console.log(
      `gtk-typegen: wrote ${colors.length} theme colors, ${icons.length} icon names.`,
    );
    app.quit();
  },
});
